variables:
 - name: SONAR_ORGANIZATION
 
trigger:
- feature-*

pool: 'Default'

steps:
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'danielmorganse'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=danielmorganse_microservicio-spring
      sonar.projectName=microservicio-spring
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    goals: 'package'
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Jacoco
    summaryFileLocation: 'coverage.xml'
- task: SonarCloudPublish@1
- task: BuildQualityChecks@8
  inputs:
    checkCoverage: true
    coverageFailOption: 'fixed'
    coverageType: 'branches'
    coverageThreshold: '85'

