variables:
  imageTag: '$(Build.BuildId)'
 
trigger:
- feature-*

pool: 'Default'

steps:
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'danielmorganse'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=danielmorganse_microservicio-spring
      sonar.projectName=microservicio-spring
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    goals: 'package'
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
- task: SonarCloudPublish@1
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-personal'
    repository: 'devdams/devops-foundation-v3-ms-spring'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    command: 'apply'
    #arguments: '-f deployment-app.yaml'
    useConfigurationFile: true
    configuration: 'deployment-app.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'dockerhub-personal'
